services:
  ftp:
    image: stilliard/pure-ftpd
    container_name: ftp_server
    ports:
      - "21:21"    
      - "30000-30009:30000-30009"  # Passive ports for data transfer
    environment: # Specify these in .env
      PUBLICHOST: "${FTP_PUBLICHOST}"  
      FTP_USER_NAME: "${FTP_USER_NAME}"  
      FTP_USER_PASS: "${FTP_USER_PASS}"  
      FTP_USER_HOME: "${FTP_USER_HOME}"  
    volumes:
      - ./ftp_data:/home/ftpusers/update  # Map local folder `ftp_data` to container's FTP storage
    restart: unless-stopped
