services:
  ftp:
    build:
      context: ./FtpServer
      dockerfile: Dockerfile
    container_name: ftp_server
    ports:
      - "21:21"
      - "30000-30010:30000-30010"
    env_file: .env 
    volumes:
      - ftp_data:/app/ftp_data
    restart: always

  web:
    build: . # will build Dockerfile in the current directory
    container_name: update-app
    ports:
      - "5000:5000"
    volumes:
      - ftp_data:/app/ftp_data  
    restart: always

  opcuaclient:
    build:
      context: ./OpcuaClient
      dockerfile: Dockerfile
    container_name: opcua-client
    ports:
      - "4840:4840"
    restart: always

volumes:
  ftp_data:
    driver: local # Store shared volume locally on PC
