services:
  ftp:
    image: zhabba/pure-ftpd-arm64
    container_name: ftp_server
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      PUBLICHOST: ""        # TODO: Use your own .env
      FTP_USER_NAME: ""     # TODO: Use your own .env
      FTP_USER_PASS: ""     # TODO: Use your own .env
      FTP_USER_HOME: "/ftp_data" 
    volumes:
      - ftp_data:/ftp_data
    restart: always

  web:
    build: . # will build Dockerfile in the current directory
    container_name: update-app
    ports:
      - "5000:5000"
    volumes:
      - ftp_data:/app/ftp_data  
    restart: always

volumes:
  ftp_data:
    driver: local # Store shared volume locally on PC
